Neos:
  Flow:
    log:
      psr3:
        loggerFactory: Flowpack\Monolog\LoggerFactory
        'Flowpack\Monolog\LoggerFactory':
          # Settings for Neos Flow's default loggers
          systemLogger:
            handler:
              streamHandler:
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/System_Development.log'
          securityLogger:
            handler:
              streamHandler:
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/Security_Development.log'
          sqlLogger:
            handler:
              streamHandler:
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/Query_Development.log'
          i18nLogger:
            handler:
              streamHandler:
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/I18n_Development.log'

